const solutionsData = [
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "AI Lead Qualification Engine",
    subtitle: "Automatically score and route inbound leads 24/7.",
    description:
      "Stop wasting sales time on unqualified prospects. Our AI engine evaluates every inbound lead against your ideal customer profile, scores them in real-time, and routes hot leads directly to your closers — while nurturing cold leads automatically.",
    features: [
      "Custom ICP scoring model trained on your data",
      "Real-time lead scoring and CRM enrichment",
      "Automated routing rules by score tier",
      "Slack / email alerts for high-intent leads",
      "Weekly performance dashboard",
    ],
    price: "$379",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "Automated Follow-Up Sequences",
    subtitle: "Never let a lead go cold again.",
    description:
      "Deploy intelligent, multi-channel follow-up sequences that feel personal but run on autopilot. Triggered by behavior, not just time delays — so every message lands at the right moment.",
    features: [
      "Behavior-triggered email + SMS sequences",
      "AI-personalized message content",
      "Multi-step nurture flows (up to 10 steps)",
      "Unsubscribe and reply handling",
      "A/B testing framework included",
    ],
    price: "$299",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "Proposal & Quote Automation",
    subtitle: "Generate polished proposals in seconds, not hours.",
    description:
      "Turn your sales conversations into beautiful, personalized proposals automatically. Integrate with your CRM to pull deal data and generate client-ready documents with one click.",
    features: [
      "CRM-connected proposal generator",
      "Branded PDF output with your templates",
      "Dynamic pricing tables and scope sections",
      "E-signature integration (DocuSign / HelloSign)",
      "Sent + opened tracking notifications",
    ],
    price: "$349",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "AI Customer Support Bot",
    subtitle: "Resolve 60–80% of support tickets without human intervention.",
    description:
      "Deploy a custom-trained AI support agent on your website, docs, or product. It handles FAQs, troubleshooting, and account questions — escalating only complex cases to your team.",
    features: [
      "Trained on your knowledge base and docs",
      "Handles FAQs, troubleshooting, billing questions",
      "Smart escalation to human agents",
      "Website chat + email channel support",
      "Monthly retraining included (3 months)",
    ],
    price: "$429",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "Revenue Operations Dashboard",
    subtitle: "One live view of every revenue metric that matters.",
    description:
      "Stop toggling between five tools to understand your pipeline. We build a unified revenue operations dashboard that pulls data from your CRM, ads, and billing into one real-time view.",
    features: [
      "Multi-source data integration (CRM, ads, billing)",
      "Live pipeline and conversion metrics",
      "Churn risk signals and MRR tracking",
      "Team performance leaderboard",
      "Weekly automated email digest",
    ],
    price: "$499",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "AI Content Repurposing Engine",
    subtitle: "Turn one piece of content into twenty.",
    description:
      "Upload a blog post, podcast transcript, or video — and get LinkedIn posts, Twitter threads, email newsletters, and short-form clips generated automatically, in your brand voice.",
    features: [
      "Brand voice profile creation",
      "Blog → LinkedIn / Twitter / Email output",
      "Podcast transcript → social clips",
      "Batch processing for content libraries",
      "CMS / Notion / Google Docs integration",
    ],
    price: "$329",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "Automated Onboarding Workflow",
    subtitle: "Deliver a 5-star onboarding experience on autopilot.",
    description:
      "Map your ideal client onboarding journey and automate every step — welcome sequences, kickoff scheduling, document collection, and progress tracking — so nothing falls through the cracks.",
    features: [
      "End-to-end onboarding workflow design",
      "Automated welcome email + portal access",
      "Document / intake form collection",
      "Kickoff call scheduling automation",
      "Progress tracking and milestone alerts",
    ],
    price: "$379",
    priceLabel: "one-time build",
  },
  {
    category: "ai-automation",
    badge: "AI & AUTOMATION",
    title: "Churn Prediction & Recovery System",
    subtitle: "Catch at-risk customers before they cancel.",
    description:
      "Our AI model monitors product usage, payment behavior, and engagement signals to flag at-risk accounts early — then triggers personalized win-back campaigns automatically.",
    features: [
      "Churn risk scoring model (custom-trained)",
      "Real-time at-risk account alerts",
      "Automated win-back email sequences",
      "Success team escalation triggers",
      "Monthly churn analytics report",
    ],
    price: "$449",
    priceLabel: "one-time build",
  },
  {
    category: "ai-voice",
    badge: "AI VOICE",
    title: "AI Inbound Voice Receptionist",
    subtitle: "Never miss a call. Never pay a receptionist.",
    description:
      "Deploy a natural-sounding AI voice agent that answers every inbound call, qualifies the caller, books appointments, and routes urgent calls to your team — 24 hours a day.",
    features: [
      "Custom AI voice matched to your brand",
      "Caller intent detection and qualification",
      "Live calendar booking via phone",
      "Call transcription + CRM logging",
      "Urgent call escalation to human team",
    ],
    price: "$549",
    priceLabel: "one-time build",
  },
  {
    category: "ai-voice",
    badge: "AI VOICE",
    title: "AI Outbound Sales Dialer",
    subtitle: "Automated outreach that sounds human.",
    description:
      "Run outbound calling campaigns with an AI voice agent that delivers personalized pitches, handles objections, and books meetings — then hands off to your closers.",
    features: [
      "Personalized outbound call scripts",
      "Objection handling response library",
      "Meeting booking and calendar sync",
      "Call recording and sentiment analysis",
      "Campaign performance dashboard",
    ],
    price: "$599",
    priceLabel: "one-time build",
  },
  {
    category: "ai-voice",
    badge: "AI VOICE",
    title: "AI Appointment Reminder System",
    subtitle: "Cut no-shows by up to 70%.",
    description:
      "Automated voice and SMS reminders that confirm, reschedule, or cancel appointments — without a single human touch. Syncs live with your calendar.",
    features: [
      "Voice + SMS multi-channel reminders",
      "Confirmation, reschedule, and cancel flows",
      "Live calendar sync (Google / Outlook / Cal.com)",
      "No-show analytics and trend reports",
      "Custom reminder timing rules",
    ],
    price: "$279",
    priceLabel: "one-time build",
  },
  {
    category: "ai-voice",
    badge: "AI VOICE",
    title: "AI Collections & Payment Recovery",
    subtitle: "Recover overdue revenue without awkward conversations.",
    description:
      "An AI voice agent that calls overdue accounts, delivers friendly payment reminders, and directs customers to a payment link — recovering cash flow around the clock.",
    features: [
      "Friendly, brand-matched voice scripts",
      "Automated payment link delivery via SMS",
      "Escalation rules for aged accounts",
      "Payment status sync to billing system",
      "Recovery rate reporting dashboard",
    ],
    price: "$479",
    priceLabel: "one-time build",
  },
  {
    category: "web",
    badge: "WEB",
    title: "High-Converting Landing Page",
    subtitle: "A landing page engineered to convert, not just look good.",
    description:
      "We design and build conversion-optimized landing pages with compelling copy architecture, trust signals, and CRO best practices baked in from the start — not bolted on later.",
    features: [
      "Conversion-focused copywriting framework",
      "Mobile-first responsive design",
      "CRO elements: social proof, urgency, guarantees",
      "Form + calendar booking integration",
      "Analytics setup (GA4 + heatmaps)",
    ],
    price: "$599",
    priceLabel: "one-time build",
  },
  {
    category: "web",
    badge: "WEB",
    title: "Website Chat-to-Lead System",
    subtitle: "Turn passive visitors into active conversations.",
    description:
      "Install an intelligent chat widget that engages visitors at the right moment, asks qualifying questions, captures contact info, and hands off warm leads to your team instantly.",
    features: [
      "Custom chat flow and qualifying questions",
      "Proactive trigger rules (scroll depth, time on page)",
      "Lead capture + CRM auto-sync",
      "Instant Slack / email lead alert",
      "Mobile-optimized chat experience",
    ],
    price: "$299",
    priceLabel: "one-time build",
  },
  {
    category: "web",
    badge: "WEB",
    title: "SEO Content Automation System",
    subtitle: "Publish optimized content at scale, consistently.",
    description:
      "Build a pipeline that researches keywords, generates SEO-optimized drafts in your brand voice, and publishes directly to your CMS — so you rank without the manual grind.",
    features: [
      "Keyword research and content calendar",
      "AI draft generation in brand voice",
      "On-page SEO optimization (meta, headers, schema)",
      "CMS auto-publish integration",
      "Monthly rankings and traffic report",
    ],
    price: "$429",
    priceLabel: "one-time build",
  },
  {
    category: "web",
    badge: "WEB",
    title: "Booking & Scheduling Automation",
    subtitle: "Eliminate the back-and-forth of scheduling forever.",
    description:
      "Deploy a fully automated booking system with smart routing, pre-call questionnaires, automated reminders, and post-call follow-ups — all connected to your calendar and CRM.",
    features: [
      "Smart booking page with routing logic",
      "Pre-call intake form and questionnaire",
      "Automated reminder sequence (email + SMS)",
      "Post-call follow-up automation",
      "CRM deal creation on booking",
    ],
    price: "$249",
    priceLabel: "one-time build",
  },
  {
    category: "web",
    badge: "WEB",
    title: "Client Portal Build",
    subtitle: "A professional self-serve hub for your clients.",
    description:
      "Give your clients a branded portal where they can track project progress, access deliverables, submit requests, and communicate — reducing email chaos for both sides.",
    features: [
      "Branded client-facing portal",
      "Project status and milestone tracking",
      "File and deliverable sharing",
      "Client request and ticket submission",
      "Team notification system",
    ],
    price: "$699",
    priceLabel: "one-time build",
  },
  {
    category: "audit-strategy",
    badge: "AUDIT & STRATEGY",
    title: "Revenue Leak Audit",
    subtitle: "Find every dollar you're leaving on the table.",
    description:
      "A deep-dive audit of your entire revenue operation — from lead capture to close to retention. We identify every bottleneck, leaky funnel, and missed automation opportunity, then hand you a prioritized action plan.",
    features: [
      "Full funnel analysis (awareness → retention)",
      "Tech stack and integration audit",
      "Bottleneck identification and impact scoring",
      "Prioritized 90-day action roadmap",
      "60-minute strategy debrief call",
    ],
    price: "$179",
    priceLabel: "flat fee",
  },
  {
    category: "audit-strategy",
    badge: "AUDIT & STRATEGY",
    title: "AI Readiness Assessment",
    subtitle: "Know exactly where AI will move the needle in your business.",
    description:
      "Not every AI tool is right for every business. We assess your workflows, data infrastructure, and team readiness to identify the highest-ROI AI opportunities — with a clear implementation roadmap.",
    features: [
      "Workflow and process mapping",
      "Data and infrastructure readiness review",
      "AI opportunity scoring by ROI potential",
      "Build vs. buy recommendation for each use case",
      "Executive summary + implementation roadmap",
    ],
    price: "$249",
    priceLabel: "flat fee",
  },
];

export default solutionsData;